[package]
name = "readfile-rs2"
version = "0.1.0"
authors = ["Amos Wenger <nospam@example.com>"]
edition = "2018"

[dependencies]
hex-slice = "0.1.4"
positioned-io = "0.2.2"
failure = "0.1.5"
byteorder = "1.3.2"
custom_debug_derive = "0.1.7"
num_enum = "0.4.1"
