# Use this to create a new angular project
services:
  angular-app: #change this name
    image: node:latest
    working_dir: /dev
    ports:
      - "127.0.0.1:4200:4200"
    stdin_open: true
    tty: true
    volumes:
      - './app:/dev/angular-app'
      - /dev/angular-app/node_modules
    command: >
      bash -c "npm install -g @angular/cli
      && ng new angular-app --defaults --directory ./angular-app
      && cd /dev/angular-app/
      && ng serve --host 0.0.0.0"