version: '3'

services:
  canvas:
    build: 
      context: .
      dockerfile: Dockerfile-canvas
    ports:
      - "8088:8088"
    container_name: caccl-api
    networks:
      - dce-net
    volumes:
      - './app-name/:/app/'
      - /app/server
      - /app/client
      - /app/node_modules
    stdin_open: true
    tty: true
  
  client:
    build: 
      context: .
      dockerfile: Dockerfile-client
    ports:
      - "3000:3000"
    container_name: react-ui
    networks:
      - dce-net
    volumes:
       - './app-name/client:/app/client'
       - /app/client/node_modules
    stdin_open: true
    tty: true

  server:
    build: 
      context: .
      dockerfile: Dockerfile-server
    ports:
      - "3080:3080"
    container_name: node-server
    networks:
      - dce-net
    volumes:
       - './app-name/server:/app/server'
       - /app/server/node_modules


networks:
  dce-net:
    driver: bridge