[package]
name = "rusty-caries"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "cr_abm"
path = "src/cr_abm/lib.rs"

[[bin]]
name = "caries"
path = "src/main.rs"

[dependencies]
structop = "0.3"
